# Generated by Django 5.2.11 on 2026-08-22 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_system', '0003_batch'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE attendance_system_student '
                        'ADD COLUMN batch_id BIGINT NULL'
                    ),
                    reverse_sql=(
                        'ALTER TABLE attendance_system_student '
                        'DROP COLUMN batch_id'
                    ),
                ),
                migrations.RunSQL(
                    sql=(
                        'CREATE INDEX attendance_system_student_batch_id_idx '
                        'ON attendance_system_student (batch_id)'
                    ),
                    reverse_sql=(
                        'DROP INDEX attendance_system_student_batch_id_idx '
                        'ON attendance_system_student'
                    ),
                ),
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE attendance_system_student '
                        'ADD CONSTRAINT attendance_system_student_batch_fk '
                        'FOREIGN KEY (batch_id) '
                        'REFERENCES attendance_system_batch (id)'
                    ),
                    reverse_sql=(
                        'ALTER TABLE attendance_system_student '
                        'DROP FOREIGN KEY attendance_system_student_batch_fk'
                    ),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='student',
                    name='batch',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='attendance_system.batch',
                    ),
                ),
            ],
        ),
    ]
